[colors]
background = #000000
background-alt = #111111
foreground = #ffffff
primary = #ffffff
secondary = #ffffff
alert = #3d59a1
disabled = #565f89

[bar/main]
width = 100%
height = 24pt
radius = 0

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 0pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.foreground}

font-0 = "FiraCode Nerd Font:size=11;2"
font-1 = "Font Awesome 6 Free:size=11;2"
font-2 = "Font Awesome 6 Brands:size=11;2"
font-3 = "Material Design Icons:size=11;2"

modules-left = xworkspaces filesystem memory cpu wlan 
modules-right = pulseaudio battery popup-calendar systray
modules-center = xwindow  

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
wm-restack = i3

; override-redirect = true

[module/systray]
type = internal/tray

format-margin = 2pt
tray-spacing = 8pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 2

label-occupied = %name%
label-occupied-padding = 2

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 2

[module/xwindow]
type = internal/xwindow
label = %title:0:35:...%

[module/pulseaudio]
type = internal/pulseaudio

; Use icons for volume levels
format-volume = <ramp-volume> <label-volume>
label-volume = %percentage%%
label-volume-foreground = ${colors.foreground}

; Use icons for mute status
format-muted = <label-muted>
label-muted = 🔇 Muted
label-muted-foreground = ${colors.disabled} 

; Ramp icons for volume levels
ramp-volume-0 = 🔈
ramp-volume-1 = 🔉
ramp-volume-2 = 🔊

; Update interval in seconds
interval = 1

; Click actions
click-right = pavucontrol &  # Open PulseAudio volume control
click-left = pamixer -t      # Toggle mute/unmute
scroll-up = pamixer -i 2     # Increase volume by 2%
scroll-down = pamixer -d 2   # Decrease volume by 2%

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#7aa2f7}%ifname%%{F#565f89} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %ifname% %essid% 

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#7aa2f7}%ifname%%{F-} %local_ip%

[module/battery]
type = internal/battery
battery = BAT0  
adapter = AC 

full-at = 98  
poll-interval = 5  

label-charging = [CHARGING] %percentage%%
label-discharging = [%time%] %percentage%%
label-full = [CHARGING] %percentage%%

format-charging = <label-charging>
format-discharging = <label-discharging>
format-full = <label-full>

[module/popup-calendar]
type = custom/script
exec = ~/.config/polybar/calendar.sh
interval = 5
click-left = ~/.config/polybar/calendar.sh --popup &

[settings]
screenchange-reload = true
pseudo-transparency = true 

; vim:ft=dosini
